// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealisTest.Data;

#nullable disable

namespace RealisTest.Data
{
    [DbContext(typeof(RealisTestContext))]
    [Migration("20220219145907_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6");

            modelBuilder.Entity("RealisTest.Models.TestInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("inputDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("inputTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestInput");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Testing",
                            inputDate = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inputTime = new DateTime(2022, 2, 19, 21, 5, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
